### ISSUE TITLE
Include some more Drogon description in live demo

### ISSUE THREAD

**Issue by rnyb** [equinor/webviz-subsurface-testdata#109]
In live demo add pictures/text in front page to decribe Drogon model

**Comment by anders-kiaer** [comment]
Maybe we could even extend the demo with information regardin model assumptions? I.e. demonstrate how markdown + pictures + tables + equations in Webviz can be used as an option to wiki for model reporting + sharing model documentation.

**Comment by anders-kiaer** [comment]
Done.

**Comment by xuhuizhou-vt** [comment]
Hi anders and rnyb,

Where can I find the description for the drogon case?

Thanks!

**Comment by xuhuizhou-vt** [comment]
thanks a lot!
