### ISSUE TITLE
FMU data for testing and examples

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-testdata#13]
We need a data set for testing and examples.

- [x] Make repository with test data (https://github.com/equinor/webviz-subsurface-testdata
- [x] Add testdata for onebyone ensemble
- [x] Add testdata for montecarlo ensembles
- [x] Add observed data (seismic, wells)
- [x] Add webviz-subsurface tests and examples using test data

**Comment by anders-kiaer** [comment]
Last point closed in #16.
